import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();


export const countryData: Prisma.CountryCreateInput[] = [

  { code: "AD", currency: "EUR", name: "Andorra", isActiveForAccount: false },
  { code: "AE", currency: "AED", name: "United Arab Emirates", isActiveForAccount: false },
  { code: "AF", currency: "AFN", name: "Afghanistan", isActiveForAccount: false },
  { code: "AG", currency: "XCD", name: "Antigua and Barbuda", isActiveForAccount: false },
  { code: "AI", currency: "XCD", name: "Anguilla", isActiveForAccount: false },
  { code: "AL", currency: "ALL", name: "Albania", isActiveForAccount: false },
  { code: "AM", currency: "AMD", name: "Armenia", isActiveForAccount: false },
  { code: "AN", currency: "ANG", name: "Netherlands Antilles", isActiveForAccount: false },
  { code: "AO", currency: "AOA", name: "Angola", isActiveForAccount: false },
  { code: "AQ", currency: "AQD", name: "Antarctica", isActiveForAccount: false },
  { code: "AR", currency: "ARS", name: "Argentina", isActiveForAccount: false },
  { code: "AS", currency: "EUR", name: "American Samoa", isActiveForAccount: false },
  { code: "AT", currency: "EUR", name: "Austria", isActiveForAccount: false },
  { code: "AU", currency: "AUD", name: "Australian", isActiveForAccount: false },
  { code: "AW", currency: "ANG", name: "Aruba", isActiveForAccount: false },
  { code: "AX", currency: "EUR", name: "Aland Islands", isActiveForAccount: false },
  { code: "AZ", currency: "AZN", name: "Azerbaijan", isActiveForAccount: false },
  { code: "BA", currency: "BAM", name: "Bosnia and Herzegovina", isActiveForAccount: false },
  { code: "BB", currency: "BBD", name: "Barbados", isActiveForAccount: false },
  { code: "BD", currency: "BDT", name: "Bangladesh", isActiveForAccount: false },
  { code: "BE", currency: "EUR", name: "Belgium", isActiveForAccount: false },
  { code: "BF", currency: "XOF", name: "Burkina Faso", isActiveForAccount: false },
  { code: "BG", currency: "BGN", name: "Bulgaria", isActiveForAccount: false },
  { code: "BH", currency: "BHD", name: "Bahrain", isActiveForAccount: false },
  { code: "BI", currency: "BIF", name: "Burundi", isActiveForAccount: false },
  { code: "BJ", currency: "XOF", name: "Benin", isActiveForAccount: false },
  { code: "BL", currency: "EUR", name: "Saint Barthelemy", isActiveForAccount: false },
  { code: "BM", currency: "BMD", name: "Bermuda", isActiveForAccount: false },
  { code: "BN", currency: "BND", name: "Brunei Darussalam", isActiveForAccount: false },
  { code: "BO", currency: "BOB", name: "Bolivia", isActiveForAccount: false },
  { code: "BR", currency: "BRL", name: "Brazil", isActiveForAccount: false },
  { code: "BS", currency: "BSD", name: "Bahamas", isActiveForAccount: false },
  { code: "BT", currency: "INR", name: "Bhutan", isActiveForAccount: false },
  { code: "BV", currency: "NOK", name: "Bouvet Island", isActiveForAccount: false },
  { code: "BW", currency: "BWP", name: "Botswana", isActiveForAccount: false },
  { code: "BY", currency: "BYR", name: "Belarus", isActiveForAccount: false },
  { code: "BZ", currency: "BZD", name: "Belize", isActiveForAccount: false },
  { code: "CA", currency: "CAD", name: "Canada", isActiveForAccount: false },
  { code: "CC", currency: "AUD", name: "Cocos (Keeling) Islands", isActiveForAccount: false },
  { code: "CD", currency: "CDF", name: "Congo (Kinshasa)", isActiveForAccount: false },
  // { code: "CD", currency: "CDF", name: "Congo-Brazzaville", isActiveForAccount: false },
  { code: "CF", currency: "XAF", name: "Central African Republic", isActiveForAccount: false },
  { code: "CG", currency: "XAF", name: "Congo Republic of the Democratic", isActiveForAccount: false },
  { code: "CH", currency: "CHF", name: "Switzerland", isActiveForAccount: false },
  { code: "CI", currency: "XOF", name: "Ivory Coast", isActiveForAccount: false },
  { code: "CK", currency: "NZD", name: "Cook Islands", isActiveForAccount: false },
  { code: "CL", currency: "CLP", name: "Chile", isActiveForAccount: false },
  { code: "CM", currency: "XAF", name: "Cameroon", isActiveForAccount: false },
  { code: "CN", currency: "CNY", name: "China", isActiveForAccount: false },
  { code: "CO", currency: "COP", name: "Colombia", isActiveForAccount: false },
  { code: "CR", currency: "CRC", name: "Costa Rica", isActiveForAccount: false },
  { code: "CU", currency: "CUP", name: "Cuba", isActiveForAccount: false },
  { code: "CV", currency: "CVE", name: "Cape Verde", isActiveForAccount: false },
  { code: "CX", currency: "AUD", name: "Christmas Island", isActiveForAccount: false },
  { code: "CY", currency: "CYP", name: "Cyprus", isActiveForAccount: false },
  { code: "CZ", currency: "CZK", name: "Czech Republic", isActiveForAccount: false },
  { code: "DE", currency: "EUR", name: "Germany", isActiveForAccount: false },
  { code: "DJ", currency: "DJF", name: "Djibouti", isActiveForAccount: false },
  { code: "DK", currency: "DKK", name: "Denmark", isActiveForAccount: false },
  { code: "DM", currency: "XCD", name: "Dominica", isActiveForAccount: false },
  { code: "DO", currency: "DOP", name: "Dominican Republic", isActiveForAccount: false },
  { code: "DZ", currency: "DZD", name: "Algeria", isActiveForAccount: false },
  { code: "EC", currency: "ECS", name: "Ecuador", isActiveForAccount: false },
  { code: "EE", currency: "EEK", name: "Estonia", isActiveForAccount: false },
  { code: "EG", currency: "EGP", name: "Egypt", isActiveForAccount: false },
  { code: "EH", currency: "MAD", name: "Western Sahara", isActiveForAccount: false },
  { code: "ER", currency: "ETB", name: "Eritrea", isActiveForAccount: false },
  { code: "ES", currency: "EUR", name: "Spain", isActiveForAccount: false },
  { code: "ET", currency: "ETB", name: "Ethiopia", isActiveForAccount: false },
  { code: "FI", currency: "EUR", name: "Finland", isActiveForAccount: false },
  { code: "FJ", currency: "FJD", name: "Fiji", isActiveForAccount: false },
  { code: "FK", currency: "FKP", name: "Falkland Islands (Malvinas)", isActiveForAccount: false },
  { code: "FM", currency: "USD", name: "Micronesia Federated States of", isActiveForAccount: false },
  { code: "FO", currency: "DKK", name: "Faroe Islands", isActiveForAccount: false },
  { code: "FR", currency: "EUR", name: "France", isActiveForAccount: false },
  { code: "GA", currency: "XAF", name: "Gabon", isActiveForAccount: false },
  { code: "GB", currency: "GBP", name: "United Kingdom", isActiveForAccount: false },
  { code: "GD", currency: "XCD", name: "Grenada", isActiveForAccount: false },
  { code: "GE", currency: "GEL", name: "Georgia", isActiveForAccount: false },
  { code: "GF", currency: "EUR", name: "French Guiana", isActiveForAccount: false },
  { code: "GG", currency: "GGP", name: "Guernsey", isActiveForAccount: false },
  { code: "GH", currency: "GHS", name: "Ghana", isActiveForAccount: false },
  { code: "GI", currency: "GIP", name: "Gibraltar", isActiveForAccount: false },
  { code: "GL", currency: "DKK", name: "Greenland", isActiveForAccount: false },
  { code: "GM", currency: "GMD", name: "Gambia", isActiveForAccount: false },
  { code: "GN", currency: "GNF", name: "Guinea", isActiveForAccount: false },
  { code: "GP", currency: "EUR", name: "Guadeloupe", isActiveForAccount: false },
  { code: "GQ", currency: "XAF", name: "Equatorial Guinea", isActiveForAccount: false },
  { code: "GR", currency: "EUR", name: "Greece", isActiveForAccount: false },
  { code: "GS", currency: "GBP", name: "South Georgia and the South Sandwich Islands", isActiveForAccount: false },
  { code: "GT", currency: "GTQ", name: "Guatemala", isActiveForAccount: false },
  { code: "GU", currency: "USD", name: "Guam", isActiveForAccount: false },
  { code: "GW", currency: "XOF", name: "Guinea-Bissau", isActiveForAccount: false },
  { code: "GY", currency: "GYD", name: "Guyana", isActiveForAccount: false },
  { code: "HK", currency: "HKD", name: "Hong Kong", isActiveForAccount: false },
  { code: "HM", currency: "AUD", name: "Heard and Mc Donald Islands", isActiveForAccount: false },
  { code: "HN", currency: "HNL", name: "Honduras", isActiveForAccount: false },
  { code: "HR", currency: "HRK", name: "Croatia (Hrvatska)", isActiveForAccount: false },
  { code: "HT", currency: "HTG", name: "Haiti", isActiveForAccount: false },
  { code: "HU", currency: "HUF", name: "Hungary", isActiveForAccount: false },
  { code: "ID", currency: "IDR", name: "Indonesia", isActiveForAccount: false },
  { code: "IE", currency: "EUR", name: "Ireland", isActiveForAccount: false },
  { code: "IL", currency: "ILS", name: "Israel", isActiveForAccount: false },
  { code: "IM", currency: "GBP", name: "Isle of Man", isActiveForAccount: false },
  { code: "IN", currency: "INR", name: "India", isActiveForAccount: false },
  { code: "IO", currency: "USD", name: "British Indian Ocean Territory", isActiveForAccount: false },
  { code: "IQ", currency: "IQD", name: "Iraq", isActiveForAccount: false },
  { code: "IR", currency: "IRR", name: "Iran (Islamic Republic of)", isActiveForAccount: false },
  { code: "IS", currency: "ISK", name: "Iceland", isActiveForAccount: false },
  { code: "IT", currency: "EUR", name: "Italy", isActiveForAccount: false },
  { code: "JE", currency: "GBP", name: "Jersey", isActiveForAccount: false },
  { code: "JM", currency: "JMD", name: "Jamaica", isActiveForAccount: false },
  { code: "JO", currency: "JOD", name: "Jordan", isActiveForAccount: false },
  { code: "JP", currency: "JPY", name: "Japan", isActiveForAccount: false },
  { code: "KE", currency: "KES", name: "Kenya", isActiveForAccount: false },
  { code: "KG", currency: "KGS", name: "Kyrgyzstan", isActiveForAccount: false },
  { code: "KH", currency: "KHR", name: "Cambodia", isActiveForAccount: false },
  { code: "KI", currency: "AUD", name: "Kiribati", isActiveForAccount: false },
  { code: "KM", currency: "KMF", name: "Comoros", isActiveForAccount: false },
  { code: "KN", currency: "XCD", name: "Saint Kitts", isActiveForAccount: false },
  { code: "KP", currency: "KPW", name: "Korea North", isActiveForAccount: false },
  { code: "KR", currency: "KRW", name: "Korea South", isActiveForAccount: false },
  { code: "KW", currency: "KWD", name: "Kuwait", isActiveForAccount: false },
  { code: "KY", currency: "KYD", name: "Cayman Islands", isActiveForAccount: false },
  { code: "KZ", currency: "KZT", name: "Kazakhstan", isActiveForAccount: false },
  { code: "LA", currency: "LAK", name: "Lao PeopleÕs Democratic Republic", isActiveForAccount: false },
  // { code: "LA", currency: "LAK", name: "Laos", isActiveForAccount: false },
  { code: "LB", currency: "LBP", name: "Lebanon", isActiveForAccount: false },
  { code: "LC", currency: "XCD", name: "Saint Lucia", isActiveForAccount: false },
  { code: "LI", currency: "CHF", name: "Liechtenstein", isActiveForAccount: false },
  { code: "LK", currency: "LKR", name: "Sri Lanka", isActiveForAccount: false },
  { code: "LR", currency: "LRD", name: "Liberia", isActiveForAccount: false },
  { code: "LS", currency: "LSL", name: "Lesotho", isActiveForAccount: false },
  { code: "LT", currency: "LTL", name: "Lithuania", isActiveForAccount: false },
  { code: "LU", currency: "EUR", name: "Luxembourg", isActiveForAccount: false },
  { code: "LV", currency: "LVL", name: "Latvia", isActiveForAccount: false },
  { code: "LY", currency: "LYD", name: "Libyan Arab Jamahiriya", isActiveForAccount: false },
  { code: "MA", currency: "MAD", name: "Morocco", isActiveForAccount: false },
  { code: "MC", currency: "EUR", name: "Monaco", isActiveForAccount: false },
  { code: "MD", currency: "MDL", name: "Moldova Republic of", isActiveForAccount: false },
  { code: "ME", currency: "EUR", name: "Montenegro", isActiveForAccount: false },
  { code: "MF", currency: "ANG", name: "Saint Martin (French part)", isActiveForAccount: false },
  { code: "MG", currency: "MGA", name: "Madagascar", isActiveForAccount: false },
  { code: "MH", currency: "USD", name: "Marshall Islands", isActiveForAccount: false },
  { code: "MK", currency: "MKD", name: "Macedonia", isActiveForAccount: false },
  { code: "ML", currency: "XOF", name: "Mali", isActiveForAccount: false },
  { code: "MM", currency: "MMK", name: "Myanmar", isActiveForAccount: false },
  { code: "MN", currency: "MNT", name: "Mongolia", isActiveForAccount: false },
  { code: "MO", currency: "MOP", name: "Macao S.A.R.", isActiveForAccount: false },
  // { code: "MO", currency: "MOP", name: "Macau", isActiveForAccount: false },
  { code: "MP", currency: "USD", name: "Northern Mariana Islands", isActiveForAccount: false },
  { code: "MQ", currency: "EUR", name: "Martinique", isActiveForAccount: false },
  { code: "MR", currency: "MRO", name: "Mauritania", isActiveForAccount: false },
  { code: "MS", currency: "XCD", name: "Montserrat", isActiveForAccount: false },
  { code: "MT", currency: "MTL", name: "Malta", isActiveForAccount: false },
  { code: "MU", currency: "MUR", name: "Mauritius", isActiveForAccount: false },
  { code: "MV", currency: "MVR", name: "Maldives", isActiveForAccount: false },
  { code: "MW", currency: "MWK", name: "Malawi", isActiveForAccount: false },
  { code: "MX", currency: "MXN", name: "Mexico", isActiveForAccount: false },
  { code: "MY", currency: "MYR", name: "Malaysia", isActiveForAccount: false },
  { code: "MZ", currency: "MZN", name: "Mozambique", isActiveForAccount: false },
  { code: "NA", currency: "NAD", name: "Namibia", isActiveForAccount: false },
  { code: "NC", currency: "XPF", name: "New Caledonia", isActiveForAccount: false },
  { code: "NE", currency: "XOF", name: "Niger", isActiveForAccount: false },
  { code: "NF", currency: "AUD", name: "Norfolk Island", isActiveForAccount: false },
  { code: "NG", currency: "NGN", name: "Nigeria", isActiveForAccount: false },
  { code: "NI", currency: "NIO", name: "Nicaragua", isActiveForAccount: false },
  { code: "NL", currency: "EUR", name: "Netherlands", isActiveForAccount: false },
  { code: "NO", currency: "NOK", name: "Norway", isActiveForAccount: false },
  { code: "NP", currency: "NPR", name: "Nepal", isActiveForAccount: false },
  { code: "NR", currency: "AUD", name: "Nauru", isActiveForAccount: false },
  { code: "NU", currency: "NZD", name: "Niue", isActiveForAccount: false },
  { code: "NZ", currency: "NZD", name: "New Zealand", isActiveForAccount: false },
  { code: "OM", currency: "OMR", name: "Oman", isActiveForAccount: false },
  { code: "PA", currency: "PAB", name: "Panama", isActiveForAccount: false },
  { code: "PE", currency: "PEN", name: "Peru", isActiveForAccount: false },
  { code: "PF", currency: "XPF", name: "French Polynesia", isActiveForAccount: false },
  { code: "PG", currency: "PGK", name: "Papua New Guinea", isActiveForAccount: false },
  { code: "PH", currency: "PHP", name: "Philippines", isActiveForAccount: false },
  { code: "PK", currency: "PKR", name: "Pakistan", isActiveForAccount: false },
  { code: "PL", currency: "PLN", name: "Poland", isActiveForAccount: false },
  { code: "PM", currency: "EUR", name: "Saint Pierre and Miquelon", isActiveForAccount: false },
  { code: "PN", currency: "NZD", name: "Pitcairn", isActiveForAccount: false },
  { code: "PR", currency: "USD", name: "Puerto Rico", isActiveForAccount: false },
  { code: "PS", currency: "JOD", name: "Palestinian Territory", isActiveForAccount: false },
  { code: "PT", currency: "EUR", name: "Portugal", isActiveForAccount: false },
  { code: "PW", currency: "USD", name: "Palau", isActiveForAccount: false },
  { code: "PY", currency: "PYG", name: "Paraguay", isActiveForAccount: false },
  { code: "QA", currency: "QAR", name: "Qatar", isActiveForAccount: false },
  { code: "RE", currency: "EUR", name: "Reunion", isActiveForAccount: false },
  { code: "RO", currency: "RON", name: "Romania", isActiveForAccount: false },
  { code: "RS", currency: "RSD", name: "Serbia", isActiveForAccount: false },
  { code: "RU", currency: "RUB", name: "Russian Federation", isActiveForAccount: false },
  { code: "RW", currency: "RWF", name: "Rwanda", isActiveForAccount: false },
  { code: "SA", currency: "SAR", name: "Saudi Arabia", isActiveForAccount: false },
  { code: "SB", currency: "SBD", name: "Solomon Islands", isActiveForAccount: false },
  { code: "SC", currency: "SCR", name: "Seychelles", isActiveForAccount: false },
  { code: "SD", currency: "SDG", name: "Sudan", isActiveForAccount: false },
  { code: "SE", currency: "SEK", name: "Sweden", isActiveForAccount: false },
  { code: "SG", currency: "SGD", name: "Singapore", isActiveForAccount: false },
  { code: "SH", currency: "GBP", name: "Saint Helena", isActiveForAccount: false },
  { code: "SI", currency: "EUR", name: "Slovenia", isActiveForAccount: false },
  { code: "SJ", currency: "NOK", name: "Svalbard and Jan Mayen Islands", isActiveForAccount: false },
  { code: "SK", currency: "SKK", name: "Slovakia (Slovak Republic)", isActiveForAccount: false },
  { code: "SL", currency: "SLL", name: "Sierra Leone", isActiveForAccount: false },
  { code: "SM", currency: "EUR", name: "San Marino", isActiveForAccount: false },
  { code: "SN", currency: "XOF", name: "Senegal", isActiveForAccount: false },
  { code: "SO", currency: "SOS", name: "Somalia", isActiveForAccount: false },
  { code: "SR", currency: "SRD", name: "Suriname", isActiveForAccount: false },
  { code: "ST", currency: "STD", name: "Sao Tome and Principe", isActiveForAccount: false },
  { code: "SV", currency: "SVC", name: "El Salvador", isActiveForAccount: false },
  { code: "SY", currency: "SYP", name: "Syrian Arab Republic", isActiveForAccount: false },
  { code: "SZ", currency: "SZL", name: "Swaziland", isActiveForAccount: false },
  { code: "TC", currency: "USD", name: "Turks and Caicos Islands", isActiveForAccount: false },
  { code: "TD", currency: "XAF", name: "Chad", isActiveForAccount: false },
  { code: "TF", currency: "EUR", name: "French Southern Territories", isActiveForAccount: false },
  { code: "TG", currency: "XOF", name: "Togo", isActiveForAccount: false },
  { code: "TH", currency: "THB", name: "Thailand", isActiveForAccount: false },
  { code: "TJ", currency: "TJS", name: "Tajikistan", isActiveForAccount: false },
  { code: "TK", currency: "NZD", name: "Tokelau", isActiveForAccount: false },
  { code: "TM", currency: "TMT", name: "Turkmenistan", isActiveForAccount: false },
  { code: "TN", currency: "TND", name: "Tunisia", isActiveForAccount: false },
  { code: "TO", currency: "TOP", name: "Tonga", isActiveForAccount: false },
  { code: "TP", currency: "IDR", name: "East Timor", isActiveForAccount: false },
  { code: "TR", currency: "TRY", name: "Turkey", isActiveForAccount: false },
  { code: "TT", currency: "TTD", name: "Trinidad and Tobago", isActiveForAccount: false },
  { code: "TV", currency: "AUD", name: "Tuvalu", isActiveForAccount: false },
  { code: "TW", currency: "TWD", name: "Taiwan", isActiveForAccount: false },
  { code: "TZ", currency: "TZS", name: "Tanzania", isActiveForAccount: false },
  { code: "UA", currency: "UAH", name: "Ukraine", isActiveForAccount: false },
  { code: "UG", currency: "UGX", name: "Uganda", isActiveForAccount: false },
  { code: "UM", currency: "USD", name: "United States Minor Outlying Islands", isActiveForAccount: false },
  { code: "US", currency: "USD", name: "United States", isActiveForAccount: false },
  { code: "USAF", currency: "USD", name: "US Armed Forces", isActiveForAccount: false },
  { code: "UY", currency: "UYU", name: "Uruguay", isActiveForAccount: false },
  { code: "UZ", currency: "UZS", name: "Uzbekistan", isActiveForAccount: false },
  { code: "VA", currency: "EUR", name: "Vatican City State (Holy See)", isActiveForAccount: false },
  { code: "VC", currency: "XCD", name: "Saint Vincent Grenadines", isActiveForAccount: false },
  { code: "VE", currency: "VEF", name: "Venezuela", isActiveForAccount: false },
  { code: "VG", currency: "USD", name: "Virgin Islands (British)", isActiveForAccount: false },
  { code: "VI", currency: "USD", name: "Virgin Islands (US)", isActiveForAccount: false },
  { code: "VN", currency: "VND", name: "Vietnam", isActiveForAccount: false },
  { code: "VU", currency: "VUV", name: "Vanuatu", isActiveForAccount: false },
  { code: "WF", currency: "XPF", name: "Wallis and Futuna Islands", isActiveForAccount: false },
  { code: "WS", currency: "EUR", name: "Samoa", isActiveForAccount: false },
  { code: "YE", currency: "YER", name: "Yemen", isActiveForAccount: false },
  { code: "YT", currency: "EUR", name: "Mayotte", isActiveForAccount: false },
  { code: "ZA", currency: "ZAR", name: "South Africa", isActiveForAccount: false },
  { code: "ZM", currency: "ZMK", name: "Zambia", isActiveForAccount: false },
  { code: "ZW", currency: "ZWD", name: "Zimbabwe", isActiveForAccount: false },
];


export default async function countrySeedData() {
  console.log(`Starting SKU data`);
  await prisma.country.deleteMany({});
  for (const u of countryData) {
    const country = await prisma.country.create({
      data: u,
    });
    console.log(`Created country with id: ${country.code}`);
  }
}