FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY tsconfig*.json ./
COPY src src
RUN npm run build

FROM node:18-alpine
WORKDIR /app/dist
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist .
ENV SCHEMA_FILE=schema.graphql
ENV VOYAGER=/graphql
ENV PORT=4000
EXPOSE $PORT
CMD ["sh", "-c", "node cli.js --port ${PORT} --schema-file ${SCHEMA_FILE} --voyager ${VOYAGER}"]
