FROM node:18-alpine as build
WORKDIR /app
ARG sourceDir=mock
COPY ${sourceDir} ./
RUN npm ci
RUN npm run build

FROM node:18-alpine
WORKDIR /app/dist
COPY --from=build /app/dist .
COPY --from=build /app/package*.json ./
RUN npm install --omit=dev
ARG SCHEMA_DIRECTORY
COPY ${SCHEMA_DIRECTORY} schema
ENV VOYAGER=/graphql
ENV PORT=4000
EXPOSE $PORT
CMD ["sh", "-c", "node cli.js --port ${PORT} --schema-directory schema --voyager ${VOYAGER}"]
