export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  DateTime: Date;
  Money: number;
  URL: any;
};

/**
 * an account is a linkage between users and advertising based business needs.
 * To this effect different forms of accounts (and “portfolios” within those accounts)
 * will give users the ability to perform different actions against different entities
 * (ex: new a line item with products attached to a brand).
 * Accounts (prior to 2023) revolve around giving users access to UC Brands
 * (in the case of a “Demand Brand Account”) or to Retailer(s) (in the case of  Supply accounts).
 */
export type Account = {
  __typename?: 'Account';
  /** The external Id of the account */
  accountExternalId?: Maybe<Scalars['ID']>;
  /** are brand keywords allowed for the account */
  allowBrandedKeywords?: Maybe<Scalars['Boolean']>;
  /** A list of Brands related to the Account */
  brands?: Maybe<BrandList>;
  campaigns?: Maybe<CampaignList>;
  /** A list of countries that Account operates in */
  countries?: Maybe<Array<Maybe<Country>>>;
  /** Currency code for the Account */
  currency?: Maybe<Currency>;
  /** Fees for the account */
  fee?: Maybe<AccountFee>;
  /** Unique Id for the Account generated by the system */
  id: Scalars['ID'];
  /** The name of the account, entered by the user on account creation */
  name: Scalars['String'];
  /** Relationship to a parent account */
  parentAccount?: Maybe<Account>;
  /** A label matching the parent account */
  parentAccountLabel?: Maybe<Scalars['String']>;
  /** list of retailers for the account */
  retailers?: Maybe<Array<Maybe<Retailer>>>;
  /** the salesforce account id */
  salesForceAccount?: Maybe<SalesForceAccount>;
  /** List of Sellers related to the Account */
  sellers?: Maybe<Array<Maybe<Seller>>>;
  /** Type of the account: supply or demand */
  type?: Maybe<AccountType>;
  /** List of Users permitted to act on the Account */
  users?: Maybe<Array<Maybe<User>>>;
};


/**
 * an account is a linkage between users and advertising based business needs.
 * To this effect different forms of accounts (and “portfolios” within those accounts)
 * will give users the ability to perform different actions against different entities
 * (ex: new a line item with products attached to a brand).
 * Accounts (prior to 2023) revolve around giving users access to UC Brands
 * (in the case of a “Demand Brand Account”) or to Retailer(s) (in the case of  Supply accounts).
 */
export type AccountRetailersArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

/** Fee structure for an Account */
export type AccountFee = {
  __typename?: 'AccountFee';
  /** Account to which the fee belongs */
  account?: Maybe<Account>;
  /** The fee charged to the account for account servicing */
  accountServicingFee?: Maybe<Scalars['Money']>;
  /** The fee charged to the demand side of the account */
  demandSideFee?: Maybe<Scalars['Money']>;
  /** The scheduled end-date of active fees or staged fees; when this is 0, the fee is not scheduled to end. */
  endDate?: Maybe<Scalars['DateTime']>;
  /** The date when the fee is no longer active. This is null when a fee is still active. */
  expiryDate?: Maybe<Scalars['DateTime']>;
  /** When true, the fee is applied to Commerce Display campaigns. */
  isCommerceDisplayManagedServiceFee?: Maybe<Scalars['Boolean']>;
  /** When true, the fee is applied to Sonsored Products campaigns. */
  isSponsoredProductsManagedServiceFee?: Maybe<Scalars['Boolean']>;
  /** The date when the fee is active. This is null when a fee is not yet active. */
  startDate?: Maybe<Scalars['DateTime']>;
  /** The fee charged to the supply side of the account */
  supplySideFee?: Maybe<Scalars['Money']>;
};

/** TODO: add description */
export type AccountSettings = {
  __typename?: 'AccountSettings';
  something?: Maybe<Scalars['String']>;
};

export enum AccountType {
  Demand = 'DEMAND',
  Supply = 'SUPPLY'
}

/** TODO: add description */
export type AccountWhiteLabelSettings = {
  __typename?: 'AccountWhiteLabelSettings';
  secondThing?: Maybe<Scalars['String']>;
  thing?: Maybe<Scalars['String']>;
};

export type Advertiser = {
  __typename?: 'Advertiser';
  campaigns?: Maybe<CampaignList>;
  id: Scalars['ID'];
  name: Scalars['String'];
};

export type AdvertiserList = {
  __typename?: 'AdvertiserList';
  advertisers?: Maybe<Array<Maybe<Advertiser>>>;
  cursor?: Maybe<Scalars['String']>;
  hasMore?: Maybe<Scalars['Boolean']>;
  limit?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  totalCount?: Maybe<Scalars['Int']>;
};

export type Attribute = BooleanAttribute | DateTimeAttribute | NumberAttribute | StringAttribute;

/** Generic audiance */
export type Audience = {
  description?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name: Scalars['String'];
  segments: Array<Maybe<Segment>>;
};


/** Generic audiance */
export type AudienceSegmentsArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

/** Audience List */
export type AudienceList = {
  __typename?: 'AudienceList';
  audiences: Array<Maybe<Audience>>;
  cursor?: Maybe<Scalars['String']>;
  hasMore?: Maybe<Scalars['Boolean']>;
  limit?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  totalCount?: Maybe<Scalars['Int']>;
};

export type BooleanAttribute = {
  __typename?: 'BooleanAttribute';
  key: Scalars['String'];
  value?: Maybe<Scalars['Boolean']>;
};

/** Brands are marketing and identity forms of business entities. */
export type Brand = {
  __typename?: 'Brand';
  brandValue?: Maybe<Scalars['Int']>;
  campaigns?: Maybe<CampaignList>;
  country?: Maybe<Scalars['String']>;
  foundedBy?: Maybe<Scalars['String']>;
  foundedIn?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  industry?: Maybe<Scalars['String']>;
  keyPeople?: Maybe<Scalars['String']>;
  lineItems?: Maybe<Array<Maybe<Lineitem>>>;
  name: Scalars['String'];
  rank?: Maybe<Scalars['Int']>;
  rating?: Maybe<Scalars['String']>;
  website?: Maybe<Scalars['String']>;
};

export type BrandList = {
  __typename?: 'BrandList';
  brands: Array<Maybe<Brand>>;
  cursor?: Maybe<Scalars['String']>;
  hasMore?: Maybe<Scalars['Boolean']>;
  limit?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  totalCount?: Maybe<Scalars['Int']>;
};

export enum BudgetType {
  Daily = 'Daily',
  Hourly = 'Hourly',
  Monthly = 'Monthly',
  Total = 'Total'
}

/** Retail Campaign */
export type Campaign = {
  __typename?: 'Campaign';
  /** Account to which the campaign belongs */
  account?: Maybe<Account>;
  advertise?: Maybe<Advertiser>;
  advertiser?: Maybe<Advertiser>;
  /** list of brands in the campaign */
  brands?: Maybe<Array<Brand>>;
  /** Budget for the campaign */
  budget?: Maybe<CampaignBudget>;
  eligibility?: Maybe<CampaignEligibility>;
  /** End date of the campaign */
  endDate?: Maybe<Scalars['DateTime']>;
  /** External Id of the account to which the campaign belongs */
  externalAccountId?: Maybe<Scalars['ID']>;
  /** External Id of the campaign, if any */
  externalCampaignId?: Maybe<Scalars['ID']>;
  id: Scalars['ID'];
  isLockout?: Maybe<Scalars['Boolean']>;
  /** list of lineitems in the campaign */
  lineitems?: Maybe<LineitemList>;
  /** Name of the campaign */
  name?: Maybe<Scalars['String']>;
  /** retailer IDs for the campaign */
  retailerIds?: Maybe<Array<Scalars['ID']>>;
  /** relailers in the campaign */
  retailers?: Maybe<Array<Retailer>>;
  /** Start date of the campaign */
  startDate?: Maybe<Scalars['DateTime']>;
  /** Status of the campaign: Active, Paused, Archived */
  status?: Maybe<CampaignStatus>;
  /** Type of the campaign: Sponsored Products or Commerce Display */
  type?: Maybe<CampaignType>;
};

/** Budget structure of Retail Campaign */
export type CampaignBudget = {
  __typename?: 'CampaignBudget';
  amount?: Maybe<Scalars['Money']>;
  cappedBudgetAmount?: Maybe<Scalars['Money']>;
  dailyPacing?: Maybe<Scalars['Money']>;
  isCapped?: Maybe<Scalars['Boolean']>;
  monthlyPacing?: Maybe<Scalars['Money']>;
  type?: Maybe<BudgetType>;
};

/** Frequency Capping structure for Retail Campaign */
export type CampaignCapping = {
  __typename?: 'CampaignCapping';
  campaign?: Maybe<Campaign>;
  count?: Maybe<Scalars['Int']>;
  duration?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
};

export enum CampaignEligibility {
  Auction = 'Auction',
  Offsite = 'Offsite',
  OffsiteCpc = 'OffsiteCpc',
  Preferred = 'Preferred',
  Unknown = 'Unknown'
}

export type CampaignList = ListPage & {
  __typename?: 'CampaignList';
  campaigns?: Maybe<Array<Maybe<Campaign>>>;
  page?: Maybe<Scalars['Int']>;
  size?: Maybe<Scalars['Int']>;
  totalCount?: Maybe<Scalars['Int']>;
};

export enum CampaignStatus {
  Active = 'Active',
  Ended = 'Ended',
  Inactive = 'Inactive',
  Scheduled = 'Scheduled',
  Unknown = 'Unknown'
}

export enum CampaignType {
  CommerceDisplay = 'CommerceDisplay',
  SponsoredProducts = 'SponsoredProducts',
  Unknown = 'Unknown'
}

/** Country */
export type Country = {
  __typename?: 'Country';
  /** ISO 3166 country code */
  code: CountryCode;
  /** currency used in country */
  currency: CurrencyCode;
  isActiveForAccount: Scalars['Boolean'];
  name: Scalars['String'];
};

/** ISO 3166 country codes */
export enum CountryCode {
  /** Andorra */
  Ad = 'AD',
  /** United Arab Emirates */
  Ae = 'AE',
  /** Afghanistan */
  Af = 'AF',
  /** Antigua and Barbuda */
  Ag = 'AG',
  /** Anguilla */
  Ai = 'AI',
  /** Albania */
  Al = 'AL',
  /** Armenia */
  Am = 'AM',
  /** Netherlands Antilles */
  An = 'AN',
  /** Angola */
  Ao = 'AO',
  /** Antarctica */
  Aq = 'AQ',
  /** Argentina */
  Ar = 'AR',
  /** American Samoa */
  As = 'AS',
  /** Austria */
  At = 'AT',
  /** Australia */
  Au = 'AU',
  /** Aruba */
  Aw = 'AW',
  /** Åland Islands */
  Ax = 'AX',
  /** Azerbaijan */
  Az = 'AZ',
  /** Bosnia and Herzegovina */
  Ba = 'BA',
  /** Barbados */
  Bb = 'BB',
  /** Bangladesh */
  Bd = 'BD',
  /** Belgium */
  Be = 'BE',
  /** Burkina Faso */
  Bf = 'BF',
  /** Bulgaria */
  Bg = 'BG',
  /** Bahrain */
  Bh = 'BH',
  /** Burundi */
  Bi = 'BI',
  /** Benin */
  Bj = 'BJ',
  /** Saint Barthélemy */
  Bl = 'BL',
  /** Bermuda */
  Bm = 'BM',
  /** Brunei Darussalam */
  Bn = 'BN',
  /** Bolivia (Plurinational State of) */
  Bo = 'BO',
  /** "Bonaire, Sint Eustatius and Saba" */
  Bq = 'BQ',
  /** Brazil */
  Br = 'BR',
  /** Bahamas */
  Bs = 'BS',
  /** Bhutan */
  Bt = 'BT',
  /** Bouvet Island */
  Bv = 'BV',
  /** Botswana */
  Bw = 'BW',
  /** Belarus */
  By = 'BY',
  /** Belize */
  Bz = 'BZ',
  /** Canada */
  Ca = 'CA',
  /** Cocos (Keeling) Islands */
  Cc = 'CC',
  /** "Congo, Democratic Republic of the" */
  Cd = 'CD',
  /** Central African Republic */
  Cf = 'CF',
  /** Congo */
  Cg = 'CG',
  /** Switzerland */
  Ch = 'CH',
  /** Côte d'Ivoire */
  Ci = 'CI',
  /** Cook Islands */
  Ck = 'CK',
  /** Chile */
  Cl = 'CL',
  /** Cameroon */
  Cm = 'CM',
  /** China */
  Cn = 'CN',
  /** Colombia */
  Co = 'CO',
  /** Costa Rica */
  Cr = 'CR',
  /** Cuba */
  Cu = 'CU',
  /** Cabo Verde */
  Cv = 'CV',
  /** Curaçao */
  Cw = 'CW',
  /** Christmas Island */
  Cx = 'CX',
  /** Cyprus */
  Cy = 'CY',
  /** Czechia */
  Cz = 'CZ',
  /** Germany */
  De = 'DE',
  /** Djibouti */
  Dj = 'DJ',
  /** Denmark */
  Dk = 'DK',
  /** Dominica */
  Dm = 'DM',
  /** Dominican Republic */
  Do = 'DO',
  /** Algeria */
  Dz = 'DZ',
  /** Ecuador */
  Ec = 'EC',
  /** Estonia */
  Ee = 'EE',
  /** Egypt */
  Eg = 'EG',
  /** Western Sahara */
  Eh = 'EH',
  /** Eritrea */
  Er = 'ER',
  /** Spain */
  Es = 'ES',
  /** Ethiopia */
  Et = 'ET',
  /** Finland */
  Fi = 'FI',
  /** Fiji */
  Fj = 'FJ',
  /** Falkland Islands (Malvinas) */
  Fk = 'FK',
  /** Micronesia (Federated States of) */
  Fm = 'FM',
  /** Faroe Islands */
  Fo = 'FO',
  /** France */
  Fr = 'FR',
  /** Gabon */
  Ga = 'GA',
  /** United Kingdom of Great Britain and Northern Ireland */
  Gb = 'GB',
  /** Grenada */
  Gd = 'GD',
  /** Georgia */
  Ge = 'GE',
  /** French Guiana */
  Gf = 'GF',
  /** Guernsey */
  Gg = 'GG',
  /** Ghana */
  Gh = 'GH',
  /** Gibraltar */
  Gi = 'GI',
  /** Greenland */
  Gl = 'GL',
  /** Gambia */
  Gm = 'GM',
  /** Guinea */
  Gn = 'GN',
  /** Guadeloupe */
  Gp = 'GP',
  /** Equatorial Guinea */
  Gq = 'GQ',
  /** Greece */
  Gr = 'GR',
  /** South Georgia and the South Sandwich Islands */
  Gs = 'GS',
  /** Guatemala */
  Gt = 'GT',
  /** Guam */
  Gu = 'GU',
  /** Guinea-Bissau */
  Gw = 'GW',
  /** Guyana */
  Gy = 'GY',
  /** Hong Kong */
  Hk = 'HK',
  /** Heard Island and McDonald Islands */
  Hm = 'HM',
  /** Honduras */
  Hn = 'HN',
  /** Croatia */
  Hr = 'HR',
  /** Haiti */
  Ht = 'HT',
  /** Hungary */
  Hu = 'HU',
  /** Indonesia */
  Id = 'ID',
  /** Ireland */
  Ie = 'IE',
  /** Israel */
  Il = 'IL',
  /** Isle of Man */
  Im = 'IM',
  /** India */
  In = 'IN',
  /** British Indian Ocean Territory */
  Io = 'IO',
  /** Iraq */
  Iq = 'IQ',
  /** Iran (Islamic Republic of) */
  Ir = 'IR',
  /** Iceland */
  Is = 'IS',
  /** Italy */
  It = 'IT',
  /** Jersey */
  Je = 'JE',
  /** Jamaica */
  Jm = 'JM',
  /** Jordan */
  Jo = 'JO',
  /** Japan */
  Jp = 'JP',
  /** Kenya */
  Ke = 'KE',
  /** Kyrgyzstan */
  Kg = 'KG',
  /** Cambodia */
  Kh = 'KH',
  /** Kiribati */
  Ki = 'KI',
  /** Comoros */
  Km = 'KM',
  /** Saint Kitts and Nevis */
  Kn = 'KN',
  /** Korea (Democratic People's Republic of) */
  Kp = 'KP',
  /** "Korea, Republic of" */
  Kr = 'KR',
  /** Kuwait */
  Kw = 'KW',
  /** Cayman Islands */
  Ky = 'KY',
  /** Kazakhstan */
  Kz = 'KZ',
  /** Lao People's Democratic Republic */
  La = 'LA',
  /** Lebanon */
  Lb = 'LB',
  /** Saint Lucia */
  Lc = 'LC',
  /** Liechtenstein */
  Li = 'LI',
  /** Sri Lanka */
  Lk = 'LK',
  /** Liberia */
  Lr = 'LR',
  /** Lesotho */
  Ls = 'LS',
  /** Lithuania */
  Lt = 'LT',
  /** Luxembourg */
  Lu = 'LU',
  /** Latvia */
  Lv = 'LV',
  /** Libya */
  Ly = 'LY',
  /** Morocco */
  Ma = 'MA',
  /** Monaco */
  Mc = 'MC',
  /** "Moldova, Republic of" */
  Md = 'MD',
  /** Montenegro */
  Me = 'ME',
  /** Saint Martin (French part) */
  Mf = 'MF',
  /** Madagascar */
  Mg = 'MG',
  /** Marshall Islands */
  Mh = 'MH',
  /** North Macedonia */
  Mk = 'MK',
  /** Mali */
  Ml = 'ML',
  /** Myanmar */
  Mm = 'MM',
  /** Mongolia */
  Mn = 'MN',
  /** Macao */
  Mo = 'MO',
  /** Northern Mariana Islands */
  Mp = 'MP',
  /** Martinique */
  Mq = 'MQ',
  /** Mauritania */
  Mr = 'MR',
  /** Montserrat */
  Ms = 'MS',
  /** Malta */
  Mt = 'MT',
  /** Mauritius */
  Mu = 'MU',
  /** Maldives */
  Mv = 'MV',
  /** Malawi */
  Mw = 'MW',
  /** Mexico */
  Mx = 'MX',
  /** Malaysia */
  My = 'MY',
  /** Mozambique */
  Mz = 'MZ',
  /** Namibia */
  Na = 'NA',
  /** New Caledonia */
  Nc = 'NC',
  /** Niger */
  Ne = 'NE',
  /** Norfolk Island */
  Nf = 'NF',
  /** Nigeria */
  Ng = 'NG',
  /** Nicaragua */
  Ni = 'NI',
  /** Netherlands */
  Nl = 'NL',
  /** Norway */
  No = 'NO',
  /** Nepal */
  Np = 'NP',
  /** Nauru */
  Nr = 'NR',
  /** Niue */
  Nu = 'NU',
  /** New Zealand */
  Nz = 'NZ',
  /** Oman */
  Om = 'OM',
  /** Panama */
  Pa = 'PA',
  /** Peru */
  Pe = 'PE',
  /** French Polynesia */
  Pf = 'PF',
  /** Papua New Guinea */
  Pg = 'PG',
  /** Philippines */
  Ph = 'PH',
  /** Pakistan */
  Pk = 'PK',
  /** Poland */
  Pl = 'PL',
  /** Saint Pierre and Miquelon */
  Pm = 'PM',
  /** Pitcairn */
  Pn = 'PN',
  /** Puerto Rico */
  Pr = 'PR',
  /** "Palestine, State of" */
  Ps = 'PS',
  /** Portugal */
  Pt = 'PT',
  /** Palau */
  Pw = 'PW',
  /** Paraguay */
  Py = 'PY',
  /** Qatar */
  Qa = 'QA',
  /** Réunion */
  Re = 'RE',
  /** Romania */
  Ro = 'RO',
  /** Serbia */
  Rs = 'RS',
  /** Russian Federation */
  Ru = 'RU',
  /** Rwanda */
  Rw = 'RW',
  /** Saudi Arabia */
  Sa = 'SA',
  /** Solomon Islands */
  Sb = 'SB',
  /** Seychelles */
  Sc = 'SC',
  /** Sudan */
  Sd = 'SD',
  /** Sweden */
  Se = 'SE',
  /** Singapore */
  Sg = 'SG',
  /** "Saint Helena, Ascension and Tristan da Cunha" */
  Sh = 'SH',
  /** Slovenia */
  Si = 'SI',
  /** Svalbard and Jan Mayen */
  Sj = 'SJ',
  /** Slovakia */
  Sk = 'SK',
  /** Sierra Leone */
  Sl = 'SL',
  /** San Marino */
  Sm = 'SM',
  /** Senegal */
  Sn = 'SN',
  /** Somalia */
  So = 'SO',
  /** Suriname */
  Sr = 'SR',
  /** South Sudan */
  Ss = 'SS',
  /** Sao Tome and Principe */
  St = 'ST',
  /** El Salvador */
  Sv = 'SV',
  /** Sint Maarten (Dutch part) */
  Sx = 'SX',
  /** Syrian Arab Republic */
  Sy = 'SY',
  /** Eswatini */
  Sz = 'SZ',
  /** Turks and Caicos Islands */
  Tc = 'TC',
  /** Chad */
  Td = 'TD',
  /** French Southern Territories */
  Tf = 'TF',
  /** Togo */
  Tg = 'TG',
  /** Thailand */
  Th = 'TH',
  /** Tajikistan */
  Tj = 'TJ',
  /** Tokelau */
  Tk = 'TK',
  /** Timor-Leste */
  Tl = 'TL',
  /** Turkmenistan */
  Tm = 'TM',
  /** Tunisia */
  Tn = 'TN',
  /** Tonga */
  To = 'TO',
  /** East Timor */
  Tp = 'TP',
  /** Turkey */
  Tr = 'TR',
  /** Trinidad and Tobago */
  Tt = 'TT',
  /** Tuvalu */
  Tv = 'TV',
  /** "Taiwan, Province of China" */
  Tw = 'TW',
  /** "Tanzania, United Republic of" */
  Tz = 'TZ',
  /** Ukraine */
  Ua = 'UA',
  /** Uganda */
  Ug = 'UG',
  /** United States Minor Outlying Islands */
  Um = 'UM',
  /** United States of America */
  Us = 'US',
  Usaf = 'USAF',
  /** Uruguay */
  Uy = 'UY',
  /** Uzbekistan */
  Uz = 'UZ',
  /** Holy See */
  Va = 'VA',
  /** Saint Vincent and the Grenadines */
  Vc = 'VC',
  /** Venezuela (Bolivarian Republic of) */
  Ve = 'VE',
  /** Virgin Islands (British) */
  Vg = 'VG',
  /** Virgin Islands (U.S.) */
  Vi = 'VI',
  /** Viet Nam */
  Vn = 'VN',
  /** Vanuatu */
  Vu = 'VU',
  /** Wallis and Futuna */
  Wf = 'WF',
  /** Samoa */
  Ws = 'WS',
  /** Yemen */
  Ye = 'YE',
  /** Mayotte */
  Yt = 'YT',
  /** South Africa */
  Za = 'ZA',
  /** Zambia */
  Zm = 'ZM',
  /** Zimbabwe */
  Zw = 'ZW'
}

/** TODO: add description */
export type CountrySettings = {
  __typename?: 'CountrySettings';
  secondThing?: Maybe<Scalars['String']>;
  thing?: Maybe<Scalars['String']>;
};

export type Creative = {
  __typename?: 'Creative';
  campaign?: Maybe<Campaign>;
  id: Scalars['ID'];
};

/** Currency */
export type Currency = {
  __typename?: 'Currency';
  /** ISO 4217 currency code */
  code: CurrencyCode;
  /** Currency name */
  name?: Maybe<Scalars['String']>;
  /** Currency Symbol */
  symbol?: Maybe<Scalars['String']>;
};

/** ISO 4217 currency codes */
export enum CurrencyCode {
  /** UAE Dirham */
  Aed = 'AED',
  /** Afghani */
  Afn = 'AFN',
  /** Lek */
  All = 'ALL',
  /** Armenian Dram */
  Amd = 'AMD',
  /** Netherlands Antillean Guilder */
  Ang = 'ANG',
  /** Kwanza */
  Aoa = 'AOA',
  Aqd = 'AQD',
  /** Argentine Peso */
  Ars = 'ARS',
  /** Australian Dollar */
  Aud = 'AUD',
  /** Aruban Florin */
  Awg = 'AWG',
  /** Azerbaijan Manat */
  Azn = 'AZN',
  /** Convertible Mark */
  Bam = 'BAM',
  /** Barbados Dollar */
  Bbd = 'BBD',
  /** Taka */
  Bdt = 'BDT',
  /** Bulgarian Lev */
  Bgn = 'BGN',
  /** Bahraini Dinar */
  Bhd = 'BHD',
  /** Burundi Franc */
  Bif = 'BIF',
  /** Bermudian Dollar */
  Bmd = 'BMD',
  /** Brunei Dollar */
  Bnd = 'BND',
  /** Boliviano */
  Bob = 'BOB',
  /** Mvdol */
  Bov = 'BOV',
  /** Brazilian Real */
  Brl = 'BRL',
  /** Bahamian Dollar */
  Bsd = 'BSD',
  /** Ngultrum */
  Btn = 'BTN',
  /** Pula */
  Bwp = 'BWP',
  /** Belarusian Ruble */
  Byn = 'BYN',
  /** Belarus Ruble */
  Byr = 'BYR',
  /** Belize Dollar */
  Bzd = 'BZD',
  /** Canadian Dollar */
  Cad = 'CAD',
  /** Congolese Franc */
  Cdf = 'CDF',
  /** WIR Euro */
  Che = 'CHE',
  /** Swiss Franc */
  Chf = 'CHF',
  /** WIR Franc */
  Chw = 'CHW',
  /** Unidad de Fomento */
  Clf = 'CLF',
  /** Chilean Peso */
  Clp = 'CLP',
  /** Yuan Renminbi */
  Cny = 'CNY',
  /** Colombian Peso */
  Cop = 'COP',
  /** Unidad de Valor Real */
  Cou = 'COU',
  /** Costa Rican Colon */
  Crc = 'CRC',
  /** Peso Convertible */
  Cuc = 'CUC',
  /** Cuban Peso */
  Cup = 'CUP',
  /** Cabo Verde Escudo */
  Cve = 'CVE',
  Cyp = 'CYP',
  /** Czech Koruna */
  Czk = 'CZK',
  /** Djibouti Franc */
  Djf = 'DJF',
  /** Danish Krone */
  Dkk = 'DKK',
  /** Dominican Peso */
  Dop = 'DOP',
  /** Algerian Dinar */
  Dzd = 'DZD',
  Ecs = 'ECS',
  Eek = 'EEK',
  /** Egyptian Pound */
  Egp = 'EGP',
  /** Nakfa */
  Ern = 'ERN',
  /** Ethiopian Birr */
  Etb = 'ETB',
  /** Euro */
  Eur = 'EUR',
  /** Fiji Dollar */
  Fjd = 'FJD',
  /** Falkland Islands Pound */
  Fkp = 'FKP',
  /** Pound Sterling */
  Gbp = 'GBP',
  /** Lari */
  Gel = 'GEL',
  Ggp = 'GGP',
  /** Ghana Cedi */
  Ghs = 'GHS',
  /** Gibraltar Pound */
  Gip = 'GIP',
  /** Dalasi */
  Gmd = 'GMD',
  /** Guinean Franc */
  Gnf = 'GNF',
  /** Quetzal */
  Gtq = 'GTQ',
  /** Guyana Dollar */
  Gyd = 'GYD',
  /** Hong Kong Dollar */
  Hkd = 'HKD',
  /** Lempira */
  Hnl = 'HNL',
  /** Kuna */
  Hrk = 'HRK',
  /** Gourde */
  Htg = 'HTG',
  /** Forint */
  Huf = 'HUF',
  /** Rupiah */
  Idr = 'IDR',
  /** New Israeli Sheqel */
  Ils = 'ILS',
  /** Indian Rupee */
  Inr = 'INR',
  /** Iraqi Dinar */
  Iqd = 'IQD',
  /** Iranian Rial */
  Irr = 'IRR',
  /** Iceland Krona */
  Isk = 'ISK',
  /** Jamaican Dollar */
  Jmd = 'JMD',
  /** Jordanian Dinar */
  Jod = 'JOD',
  /** Yen */
  Jpy = 'JPY',
  /** Kenyan Shilling */
  Kes = 'KES',
  /** Som */
  Kgs = 'KGS',
  /** Riel */
  Khr = 'KHR',
  /** Comorian Franc */
  Kmf = 'KMF',
  /** North Korean Won */
  Kpw = 'KPW',
  /** Won */
  Krw = 'KRW',
  /** Kuwaiti Dinar */
  Kwd = 'KWD',
  /** Cayman Islands Dollar */
  Kyd = 'KYD',
  /** Tenge */
  Kzt = 'KZT',
  /** Lao Kip */
  Lak = 'LAK',
  /** Lebanese Pound */
  Lbp = 'LBP',
  /** Sri Lanka Rupee */
  Lkr = 'LKR',
  /** Liberian Dollar */
  Lrd = 'LRD',
  /** Loti */
  Lsl = 'LSL',
  Ltl = 'LTL',
  Lvl = 'LVL',
  /** Libyan Dinar */
  Lyd = 'LYD',
  /** Moroccan Dirham */
  Mad = 'MAD',
  /** Moldovan Leu */
  Mdl = 'MDL',
  /** Malagasy Ariary */
  Mga = 'MGA',
  /** Denar */
  Mkd = 'MKD',
  /** Kyat */
  Mmk = 'MMK',
  /** Tugrik */
  Mnt = 'MNT',
  /** Pataca */
  Mop = 'MOP',
  Mro = 'MRO',
  /** Ouguiya */
  Mru = 'MRU',
  Mtl = 'MTL',
  /** Mauritius Rupee */
  Mur = 'MUR',
  /** Rufiyaa */
  Mvr = 'MVR',
  /** Malawi Kwacha */
  Mwk = 'MWK',
  /** Mexican Peso */
  Mxn = 'MXN',
  /** Mexican Unidad de Inversion (UDI) */
  Mxv = 'MXV',
  /** Malaysian Ringgit */
  Myr = 'MYR',
  /** Mozambique Metical */
  Mzn = 'MZN',
  /** Namibia Dollar */
  Nad = 'NAD',
  /** Naira */
  Ngn = 'NGN',
  /** Cordoba Oro */
  Nio = 'NIO',
  /** Norwegian Krone */
  Nok = 'NOK',
  /** Nepalese Rupee */
  Npr = 'NPR',
  /** New Zealand Dollar */
  Nzd = 'NZD',
  /** Rial Omani */
  Omr = 'OMR',
  /** Balboa */
  Pab = 'PAB',
  /** Sol */
  Pen = 'PEN',
  /** Kina */
  Pgk = 'PGK',
  /** Philippine Peso */
  Php = 'PHP',
  /** Pakistan Rupee */
  Pkr = 'PKR',
  /** Zloty */
  Pln = 'PLN',
  /** Guarani */
  Pyg = 'PYG',
  /** Qatari Rial */
  Qar = 'QAR',
  /** Romanian Leu */
  Ron = 'RON',
  /** Serbian Dinar */
  Rsd = 'RSD',
  /** Russian Ruble */
  Rub = 'RUB',
  /** Rwanda Franc */
  Rwf = 'RWF',
  /** Saudi Riyal */
  Sar = 'SAR',
  /** Solomon Islands Dollar */
  Sbd = 'SBD',
  /** Seychelles Rupee */
  Scr = 'SCR',
  /** Sudanese Pound */
  Sdg = 'SDG',
  /** Swedish Krona */
  Sek = 'SEK',
  /** Singapore Dollar */
  Sgd = 'SGD',
  /** Saint Helena Pound */
  Shp = 'SHP',
  Skk = 'SKK',
  /** Leone */
  Sll = 'SLL',
  /** Somali Shilling */
  Sos = 'SOS',
  /** Surinam Dollar */
  Srd = 'SRD',
  Ssk = 'SSK',
  /** South Sudanese Pound */
  Ssp = 'SSP',
  Std = 'STD',
  /** Dobra */
  Stn = 'STN',
  /** El Salvador Colon */
  Svc = 'SVC',
  /** Syrian Pound */
  Syp = 'SYP',
  /** Lilangeni */
  Szl = 'SZL',
  /** Baht */
  Thb = 'THB',
  /** Somoni */
  Tjs = 'TJS',
  /** Turkmenistan New Manat */
  Tmt = 'TMT',
  /** Tunisian Dinar */
  Tnd = 'TND',
  /** Pa'anga */
  Top = 'TOP',
  /** Turkish Lira */
  Try = 'TRY',
  /** Trinidad and Tobago Dollar */
  Ttd = 'TTD',
  /** New Taiwan Dollar */
  Twd = 'TWD',
  /** Tanzanian Shilling */
  Tzs = 'TZS',
  /** Hryvnia */
  Uah = 'UAH',
  /** Uganda Shilling */
  Ugx = 'UGX',
  /** US Dollar */
  Usd = 'USD',
  /** Uruguay Peso en Unidades Indexadas (UI) */
  Uyi = 'UYI',
  /** Peso Uruguayo */
  Uyu = 'UYU',
  /** Unidad Previsional */
  Uyw = 'UYW',
  /** Uzbekistan Sum */
  Uzs = 'UZS',
  Vef = 'VEF',
  /** Bolívar Soberano */
  Ves = 'VES',
  /** Dong */
  Vnd = 'VND',
  /** Vatu */
  Vuv = 'VUV',
  /** Tala */
  Wst = 'WST',
  /** CFA Franc BEAC */
  Xaf = 'XAF',
  /** Silver */
  Xag = 'XAG',
  /** Gold */
  Xau = 'XAU',
  /** Bond Markets Unit European Composite Unit (EURCO) */
  Xba = 'XBA',
  /** Bond Markets Unit European Monetary Unit (E.M.U.-6) */
  Xbb = 'XBB',
  /** Bond Markets Unit European Unit of Account 9 (E.U.A.-9) */
  Xbc = 'XBC',
  /** Bond Markets Unit European Unit of Account 17 (E.U.A.-17) */
  Xbd = 'XBD',
  /** East Caribbean Dollar */
  Xcd = 'XCD',
  /** SDR (Special Drawing Right) */
  Xdr = 'XDR',
  /** CFA Franc BCEAO */
  Xof = 'XOF',
  /** Palladium */
  Xpd = 'XPD',
  /** CFP Franc */
  Xpf = 'XPF',
  /** Platinum */
  Xpt = 'XPT',
  /** Sucre */
  Xsu = 'XSU',
  /** Codes specifically reserved for testing purposes */
  Xts = 'XTS',
  /** ADB Unit of Account */
  Xua = 'XUA',
  /** Yemeni Rial */
  Yer = 'YER',
  /** Rand */
  Zar = 'ZAR',
  Zmk = 'ZMK',
  /** Zambian Kwacha */
  Zmw = 'ZMW',
  Zwd = 'ZWD',
  /** Zimbabwe Dollar */
  Zwl = 'ZWL'
}

/** TODO: add description */
export type CurrencySettings = {
  __typename?: 'CurrencySettings';
  something?: Maybe<Scalars['String']>;
};

export type DateTimeAttribute = {
  __typename?: 'DateTimeAttribute';
  key: Scalars['String'];
  value?: Maybe<Scalars['DateTime']>;
};

export type EmailAddress = {
  __typename?: 'EmailAddress';
  emailAddress?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['ID']>;
  linkedTo?: Maybe<Array<Maybe<IdentificationLink>>>;
  verification?: Maybe<Verification>;
};

export type ExternalAccount = {
  __typename?: 'ExternalAccount';
  approvedScopes?: Maybe<Scalars['String']>;
  emailAddress?: Maybe<Scalars['String']>;
  externalId?: Maybe<Scalars['String']>;
  firstName?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['String']>;
  identificationId?: Maybe<Scalars['String']>;
  imageUrl?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  lastName?: Maybe<Scalars['String']>;
  provider?: Maybe<Scalars['String']>;
  publicMetadata?: Maybe<Array<Maybe<Attribute>>>;
  username?: Maybe<Scalars['String']>;
  verification?: Maybe<Verification>;
};

export enum FinancialStatus {
  Active = 'Active',
  BudgetHitDaily = 'BudgetHitDaily',
  BudgetHitMonthly = 'BudgetHitMonthly',
  BudgetHitTotal = 'BudgetHitTotal',
  NoFunds = 'NoFunds',
  Unknown = 'Unknown'
}

export type IdentificationLink = {
  __typename?: 'IdentificationLink';
  id?: Maybe<Scalars['ID']>;
  type?: Maybe<Scalars['String']>;
};

export type Lineitem = {
  __typename?: 'Lineitem';
  audience?: Maybe<Audience>;
  budget?: Maybe<LineitemBudget>;
  campaign?: Maybe<Campaign>;
  creatives?: Maybe<Array<Maybe<Creative>>>;
  endDate?: Maybe<Scalars['DateTime']>;
  financialStatus?: Maybe<FinancialStatus>;
  id: Scalars['ID'];
  name: Scalars['String'];
  pages?: Maybe<Array<Maybe<LineitemPage>>>;
  retailer?: Maybe<Retailer>;
  startDate?: Maybe<Scalars['DateTime']>;
  status?: Maybe<LineitemStatus>;
};

export type LineitemBudget = {
  __typename?: 'LineitemBudget';
  amount?: Maybe<Scalars['Money']>;
  isCapped?: Maybe<Scalars['Boolean']>;
  type?: Maybe<BudgetType>;
};

export type LineitemList = ListOffsetLimit & {
  __typename?: 'LineitemList';
  limit?: Maybe<Scalars['Int']>;
  lineitems?: Maybe<Array<Maybe<Lineitem>>>;
  offset?: Maybe<Scalars['Int']>;
  totalCount?: Maybe<Scalars['Int']>;
};

export type LineitemPage = {
  __typename?: 'LineitemPage';
  environment?: Maybe<PageEnvironment>;
  includeSubchildren?: Maybe<Scalars['Boolean']>;
  isExclusion?: Maybe<Scalars['Boolean']>;
  taxonomy?: Maybe<Scalars['String']>;
  type?: Maybe<PageType>;
};

export enum LineitemStatus {
  Active = 'Active',
  Archived = 'Archived',
  Paused = 'Paused'
}

/** Cursor Pagination */
export type ListCursor = {
  /** The cursor to start returning results from */
  cursor?: Maybe<Scalars['String']>;
  /** The maximum number of items to return */
  limit?: Maybe<Scalars['Int']>;
  /** Total number of items in the list */
  totalCount?: Maybe<Scalars['Int']>;
};

/** Offset and Limit Pagination */
export type ListOffsetLimit = {
  /** The maximum number of items to return */
  limit?: Maybe<Scalars['Int']>;
  /** The offset in the collection */
  offset?: Maybe<Scalars['Int']>;
  /** Total number of items in the list */
  totalCount?: Maybe<Scalars['Int']>;
};

/** Page style Pagination */
export type ListPage = {
  /** The page to start returning results from */
  page?: Maybe<Scalars['Int']>;
  /** The maximum number of items to return */
  size?: Maybe<Scalars['Int']>;
  /** Total number of items in the list */
  totalCount?: Maybe<Scalars['Int']>;
};

/**
 * Look back window is the attribution window and refers to the acceptable number of days between the click and the conversion.
 *
 * See: https://criteo.atlassian.net/wiki/spaces/RMP/pages/1503109321/8.1.7.4.+Attribution+-+Look-back+Windows+and+How+to+Customize+Them
 */
export enum LookbackWindow {
  /** 30 Days */
  OneMonth = 'OneMonth',
  /** 7 Days */
  OneWeek = 'OneWeek',
  /** 14 Days */
  TwoWeeks = 'TwoWeeks'
}

/** SKU matching level is used in Attribution and is the level of granularity at which the SKU is matched. */
export enum MatchLevel {
  /** Matches on the exact SKU */
  Sku = 'Sku',
  /** Matches on SKU Category */
  SkuCategory = 'SkuCategory',
  /** Matches on SKU Category and SKU Brand */
  SkuCategoryBrand = 'SkuCategoryBrand'
}

export type Mutation = {
  __typename?: 'Mutation';
  /** activates the Lineitems by ID and returns the lineitems */
  activateLineitems: Array<Maybe<Lineitem>>;
  activateRetailer?: Maybe<Retailer>;
  addAccountSeller?: Maybe<Seller>;
  addDemandAccountBrands?: Maybe<Array<Maybe<Brand>>>;
  addRemoveBrandsToPortfolio?: Maybe<Portfolio>;
  addTaxonomyManually?: Maybe<Sku>;
  addUser?: Maybe<User>;
  applyAccountFees?: Maybe<AccountFee>;
  /** archives the Lineitems by ID and returns the lineitems */
  archiveLineitems: Array<Maybe<Lineitem>>;
  configureTOP?: Maybe<Scalars['Boolean']>;
  connectAccountToRetailer?: Maybe<Account>;
  deactivateRetailer?: Maybe<Retailer>;
  enableBrandedKeywords?: Maybe<Account>;
  grantBrandAccessForUser?: Maybe<Portfolio>;
  mapAccountRetailers?: Maybe<Array<Maybe<Retailer>>>;
  modifyAccoutSettings?: Maybe<AccountSettings>;
  modifyCountrySettings?: Maybe<CountrySettings>;
  modifyCurrencySettings?: Maybe<CurrencySettings>;
  modifyPortfolioName?: Maybe<Portfolio>;
  modifyReportingLabel?: Maybe<ReportingLabel>;
  newAccount?: Maybe<Account>;
  newBrand?: Maybe<Brand>;
  /** creates a new campaign and returns the campaign */
  newCampaign?: Maybe<Campaign>;
  /** creates a new lineitem and returns the lineitem */
  newLineitem?: Maybe<Lineitem>;
  newPortfolio?: Maybe<Portfolio>;
  newPrivateMarketAccount?: Maybe<PrivateMarketAccount>;
  newRetailer?: Maybe<Retailer>;
  /** pauses the Lineitems by ID and returns the lineitems */
  pauseLineitems: Array<Maybe<Lineitem>>;
  removeAccountRetailer?: Maybe<Retailer>;
  removeAccountSeller?: Maybe<Seller>;
  removeAccountUser?: Maybe<User>;
  removeBrandAccessForUser?: Maybe<User>;
  removeDemandAccountBrands?: Maybe<Array<Maybe<Brand>>>;
  removePortfolio?: Maybe<Portfolio>;
  removePortfolioFromAccount?: Maybe<Portfolio>;
  setRetailerPreferencesDefaultValues?: Maybe<RetailerPreferences>;
  setupWhiteLabelSettings?: Maybe<AccountWhiteLabelSettings>;
  updateSKUs?: Maybe<Array<Maybe<Sku>>>;
  updateUser?: Maybe<User>;
  updateUserName?: Maybe<User>;
  updateWhiteLabelSettings?: Maybe<AccountWhiteLabelSettings>;
};


export type MutationActivateLineitemsArgs = {
  lineitemIds: Array<InputMaybe<Scalars['ID']>>;
};


export type MutationActivateRetailerArgs = {
  id: Scalars['ID'];
};


export type MutationAddAccountSellerArgs = {
  accountId: Scalars['ID'];
  sellerId: Scalars['ID'];
};


export type MutationAddDemandAccountBrandsArgs = {
  accountId: Scalars['ID'];
  brandIds: Array<Scalars['ID']>;
};


export type MutationAddRemoveBrandsToPortfolioArgs = {
  brandIds: Array<Scalars['ID']>;
  portfolioId: Scalars['ID'];
};


export type MutationAddTaxonomyManuallyArgs = {
  skyKey: Scalars['ID'];
  taxonomy: Array<Scalars['String']>;
};


export type MutationAddUserArgs = {
  accountId: Scalars['ID'];
  userId: Scalars['ID'];
};


export type MutationApplyAccountFeesArgs = {
  accountId: Scalars['ID'];
  fees: NewAccountFee;
};


export type MutationArchiveLineitemsArgs = {
  lineitemIds: Array<InputMaybe<Scalars['ID']>>;
};


export type MutationConnectAccountToRetailerArgs = {
  accountId: Scalars['ID'];
  retailerId: Scalars['ID'];
};


export type MutationDeactivateRetailerArgs = {
  id: Scalars['ID'];
};


export type MutationEnableBrandedKeywordsArgs = {
  accountId: Scalars['ID'];
};


export type MutationGrantBrandAccessForUserArgs = {
  brandId: Scalars['ID'];
  portfolioId: Scalars['ID'];
  userId: Scalars['ID'];
};


export type MutationMapAccountRetailersArgs = {
  accountId: Scalars['ID'];
  retailerIds: Array<InputMaybe<Scalars['ID']>>;
};


export type MutationModifyAccoutSettingsArgs = {
  accountId: Scalars['ID'];
  settings: UpdateAccountSettings;
};


export type MutationModifyCountrySettingsArgs = {
  accountId: Scalars['ID'];
  countryId?: InputMaybe<Scalars['ID']>;
};


export type MutationModifyCurrencySettingsArgs = {
  accountId: Scalars['ID'];
  currency: CurrencyCode;
};


export type MutationModifyPortfolioNameArgs = {
  name: Scalars['String'];
  portfolioId: Scalars['ID'];
};


export type MutationModifyReportingLabelArgs = {
  accountId: Scalars['ID'];
  label: Scalars['String'];
};


export type MutationNewAccountArgs = {
  account: NewAccount;
};


export type MutationNewBrandArgs = {
  brand: NewBrand;
};


export type MutationNewCampaignArgs = {
  advertiserId: Scalars['ID'];
  campaign: NewCampaign;
};


export type MutationNewLineitemArgs = {
  campaignId: Scalars['ID'];
  lineitem: NewLineitem;
};


export type MutationNewPortfolioArgs = {
  portfolio: NewPortfolio;
};


export type MutationNewPrivateMarketAccountArgs = {
  accountId: Scalars['ID'];
  privateMarketAccount: NewPrivateMarketAccount;
};


export type MutationNewRetailerArgs = {
  retailer: NewRetailer;
};


export type MutationPauseLineitemsArgs = {
  lineitemIds: Array<InputMaybe<Scalars['ID']>>;
};


export type MutationRemoveAccountRetailerArgs = {
  accountId: Scalars['ID'];
  retailerId: Scalars['ID'];
};


export type MutationRemoveAccountSellerArgs = {
  accountId: Scalars['ID'];
  sellerId: Scalars['ID'];
};


export type MutationRemoveAccountUserArgs = {
  accountId: Scalars['ID'];
  userId: Scalars['ID'];
};


export type MutationRemoveBrandAccessForUserArgs = {
  brandId: Scalars['ID'];
  userId: Scalars['ID'];
};


export type MutationRemoveDemandAccountBrandsArgs = {
  accountId: Scalars['ID'];
  brandIds: Array<Scalars['ID']>;
};


export type MutationRemovePortfolioArgs = {
  portfolioId: Scalars['ID'];
};


export type MutationRemovePortfolioFromAccountArgs = {
  accountId: Scalars['ID'];
  portfolioId: Scalars['ID'];
};


export type MutationSetRetailerPreferencesDefaultValuesArgs = {
  preferences: NewDefaultPreferences;
};


export type MutationSetupWhiteLabelSettingsArgs = {
  accountId: Scalars['ID'];
  whiteLabelSettings: NewWhiteLabelSettings;
};


export type MutationUpdateSkUsArgs = {
  skuUpdates?: InputMaybe<Array<InputMaybe<SkuUpdate>>>;
};


export type MutationUpdateUserNameArgs = {
  accountId: Scalars['ID'];
  name: Scalars['String'];
  userId: Scalars['ID'];
};


export type MutationUpdateWhiteLabelSettingsArgs = {
  accountId: Scalars['ID'];
  whiteLabelSettings: UpdateWhiteLabelSettings;
};

export type NewAccount = {
  accountExternalId?: InputMaybe<Scalars['ID']>;
  allowBrandedKeywords: Scalars['Boolean'];
  countries: Array<InputMaybe<Scalars['ID']>>;
  currency: CurrencyCode;
  fee?: InputMaybe<NewAccountFee>;
  name: Scalars['String'];
  parentAccount?: InputMaybe<Scalars['ID']>;
  parentAccountLabel?: InputMaybe<Scalars['String']>;
  salesForceAccount?: InputMaybe<NewSalesForeAccount>;
  type: AccountType;
};

export type NewAccountFee = {
  accountServicingFee?: InputMaybe<Scalars['Money']>;
  demandSideFee: Scalars['Money'];
  endDate: Scalars['DateTime'];
  isCommerceDisplayManagedServiceFee?: InputMaybe<Scalars['Boolean']>;
  isSponsoredProductsManagedServiceFee?: InputMaybe<Scalars['Boolean']>;
  startDate: Scalars['DateTime'];
  supplySideFee: Scalars['Money'];
};

export type NewBrand = {
  name: Scalars['String'];
};

/** Input type for creating a new campaign (RM). */
export type NewCampaign = {
  /** budget for the campaign, including amount and budget type ( Total, Daily, Monthly, Hourly ) */
  budget: NewCampaignBudget;
  clickLookbackWindow?: InputMaybe<LookbackWindow>;
  clickMatchLevel?: InputMaybe<MatchLevel>;
  /** end date of the campaign */
  endDate: Scalars['DateTime'];
  isLockout?: InputMaybe<Scalars['Boolean']>;
  /** name of the campaign */
  name: Scalars['String'];
  /** start date of the campaign */
  startDate: Scalars['DateTime'];
  /** type of the campaign (Unknown, SponsoredProducts, CommerceDisplay) */
  type?: InputMaybe<CampaignType>;
  unexposedRate?: InputMaybe<Scalars['Money']>;
  viewLookbackWindow?: InputMaybe<LookbackWindow>;
  viewMatchLevel?: InputMaybe<MatchLevel>;
};

export type NewCampaignBudget = {
  amount?: InputMaybe<Scalars['Money']>;
  cappedBudgetAmount?: InputMaybe<Scalars['Money']>;
  dailyPacing?: InputMaybe<Scalars['Money']>;
  isCapped: Scalars['Boolean'];
  monthlyPacing?: InputMaybe<Scalars['Money']>;
  type: BudgetType;
};

export type NewDefaultPreferences = {
  defaultValues?: InputMaybe<Array<InputMaybe<NewDefaultValue>>>;
  retailerId: Scalars['ID'];
};

export type NewDefaultValue = {
  key: Scalars['String'];
  value: Scalars['String'];
};

export type NewLineitem = {
  budget: NewLineitemBudget;
  endDate: Scalars['DateTime'];
  name: Scalars['String'];
  pages: Array<NewLineitemPage>;
  startDate: Scalars['DateTime'];
};

export type NewLineitemBudget = {
  amount: Scalars['Money'];
  isCapped: Scalars['Boolean'];
  type: BudgetType;
};

export type NewLineitemPage = {
  Taxonomy: Scalars['String'];
  environment: PageEnvironment;
  includeSubchildren: Scalars['Boolean'];
  isExclusion: Scalars['Boolean'];
  type: PageType;
};

export type NewPortfolio = {
  account: Scalars['ID'];
  brands: Array<InputMaybe<Scalars['ID']>>;
  name: Scalars['String'];
};

export type NewPrivateMarketAccount = {
  account: Scalars['ID'];
  name: Scalars['String'];
};

export type NewRetailer = {
  name: Scalars['String'];
};

export type NewSalesForeAccount = {
  favoriteColor?: InputMaybe<Scalars['String']>;
  name: Scalars['String'];
  shoeSize?: InputMaybe<Scalars['Float']>;
};

export type NewWhiteLabelSettings = {
  things?: InputMaybe<Scalars['String']>;
};

export type NumberAttribute = {
  __typename?: 'NumberAttribute';
  key: Scalars['String'];
  value?: Maybe<Scalars['Int']>;
};

/** Offsite audiance */
export type OffsiteAudience = Audience & {
  __typename?: 'OffsiteAudience';
  description?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name: Scalars['String'];
  segments: Array<Maybe<Segment>>;
};


/** Offsite audiance */
export type OffsiteAudienceSegmentsArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

/** Onsite audiance */
export type OnsiteAudience = Audience & {
  __typename?: 'OnsiteAudience';
  description?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name: Scalars['String'];
  segments: Array<Maybe<Segment>>;
};


/** Onsite audiance */
export type OnsiteAudienceSegmentsArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

export enum PageEnvironment {
  App = 'App',
  Mobile = 'Mobile',
  Web = 'Web'
}

export enum PageType {
  Brand = 'Brand',
  Category = 'Category',
  Other = 'Other',
  Product = 'Product',
  Search = 'Search'
}

export type PhoneNumber = {
  __typename?: 'PhoneNumber';
  defaultSecondFactor?: Maybe<Scalars['Boolean']>;
  id?: Maybe<Scalars['ID']>;
  linkedTo?: Maybe<Array<Maybe<IdentificationLink>>>;
  phoneNumber?: Maybe<Scalars['String']>;
  reservedForSecondFactor?: Maybe<Scalars['Boolean']>;
  verification?: Maybe<Verification>;
};

/** TODO: add description */
export type Portfolio = {
  __typename?: 'Portfolio';
  accounts?: Maybe<Array<Maybe<Account>>>;
  id: Scalars['ID'];
  name?: Maybe<Scalars['String']>;
};

export type PrivateMarketAccount = {
  __typename?: 'PrivateMarketAccount';
  favoriteColor?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name?: Maybe<Scalars['String']>;
  shoeSize?: Maybe<Scalars['Float']>;
};

export type Query = {
  __typename?: 'Query';
  /**
   * retrives a single account by ID
   * findAccount
   */
  account?: Maybe<Account>;
  /**
   * retrives a list of accounts for me, optionally filtered by name
   * if no accounts are fount an empty list will be returned
   */
  accounts: Array<Maybe<Account>>;
  advertiser?: Maybe<Advertiser>;
  /** Get all audiances */
  audience?: Maybe<Audience>;
  audiences: AudienceList;
  brand?: Maybe<Brand>;
  brands?: Maybe<BrandList>;
  /** retrives a single campaign by ID */
  campaign?: Maybe<Campaign>;
  /** retrives a list of campaigns for an account or retailer */
  campaigns?: Maybe<CampaignList>;
  /** Get a list of countries optionally filtered by name */
  countries: Array<Maybe<Country>>;
  /** Get a single country */
  country?: Maybe<Country>;
  /** Get a list of currencies optionally filtered by name */
  currencies: Array<Maybe<Currency>>;
  /** Get a single currency by id or code */
  currency?: Maybe<Currency>;
  /** retrives a single lineitem by ID */
  lineitem?: Maybe<Lineitem>;
  /** retrives a list of lineitems for a campaign */
  lineitems?: Maybe<LineitemList>;
  me?: Maybe<User>;
  retailer?: Maybe<Retailer>;
  retailers: RetailerList;
  segment?: Maybe<Segment>;
  segments: Array<Maybe<Segment>>;
  sku?: Maybe<Sku>;
  /** List of SKUs by search phrase */
  skus?: Maybe<SkuList>;
  user?: Maybe<User>;
  users?: Maybe<Array<Maybe<User>>>;
};


export type QueryAccountArgs = {
  accountId: Scalars['ID'];
};


export type QueryAccountsArgs = {
  retailerId?: InputMaybe<Scalars['ID']>;
  searchName?: InputMaybe<Scalars['String']>;
};


export type QueryAdvertiserArgs = {
  id: Scalars['ID'];
};


export type QueryAudienceArgs = {
  audienceId: Scalars['ID'];
};


export type QueryAudiencesArgs = {
  someArgument?: InputMaybe<Scalars['String']>;
};


export type QueryBrandArgs = {
  brandId: Scalars['ID'];
};


export type QueryBrandsArgs = {
  brandIds?: InputMaybe<Array<InputMaybe<Scalars['ID']>>>;
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};


export type QueryCampaignArgs = {
  id: Scalars['ID'];
};


export type QueryCampaignsArgs = {
  accountId?: InputMaybe<Scalars['ID']>;
  brandId?: InputMaybe<Scalars['ID']>;
  page?: InputMaybe<Scalars['Int']>;
  retailerId?: InputMaybe<Scalars['ID']>;
  size?: InputMaybe<Scalars['Int']>;
};


export type QueryCountriesArgs = {
  countryCodes?: InputMaybe<Array<InputMaybe<CountryCode>>>;
  searchName?: InputMaybe<Scalars['String']>;
};


export type QueryCountryArgs = {
  code: CountryCode;
};


export type QueryCurrenciesArgs = {
  searchName?: InputMaybe<Scalars['String']>;
};


export type QueryCurrencyArgs = {
  code?: InputMaybe<CurrencyCode>;
  id?: InputMaybe<Scalars['ID']>;
};


export type QueryLineitemArgs = {
  id: Scalars['ID'];
};


export type QueryLineitemsArgs = {
  campaignId: Scalars['ID'];
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};


export type QueryRetailerArgs = {
  id: Scalars['ID'];
};


export type QueryRetailersArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
  retailerIds?: InputMaybe<Array<Scalars['ID']>>;
};


export type QuerySegmentArgs = {
  segmentId: Scalars['ID'];
};


export type QuerySegmentsArgs = {
  someArgument?: InputMaybe<Scalars['String']>;
};


export type QuerySkuArgs = {
  skuKey: Scalars['ID'];
};


export type QuerySkusArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
  search?: InputMaybe<Scalars['String']>;
};


export type QueryUserArgs = {
  userId: Scalars['ID'];
};


export type QueryUsersArgs = {
  searchCriteria?: InputMaybe<Scalars['String']>;
};

/** TODO: add description */
export type ReportingLabel = {
  __typename?: 'ReportingLabel';
  something?: Maybe<Scalars['String']>;
};

export type Retailer = {
  __typename?: 'Retailer';
  /** account related to the retailer */
  account?: Maybe<Account>;
  campaigns?: Maybe<CampaignList>;
  countriesOfOperation?: Maybe<Scalars['Int']>;
  countryOfOrigin?: Maybe<Scalars['String']>;
  expermentalConfig?: Maybe<Array<Maybe<RetailerExpermentalConfig>>>;
  id: Scalars['ID'];
  /** Lineitems for the retailer */
  lineitems?: Maybe<Array<Maybe<Lineitem>>>;
  name: Scalars['String'];
  operationalFormat?: Maybe<Scalars['String']>;
  parentCompanyNetIncome?: Maybe<Scalars['Int']>;
  parentRevenue?: Maybe<Scalars['Int']>;
  preferences?: Maybe<RetailerPreferences>;
  rank?: Maybe<Scalars['Int']>;
  retailRevenue?: Maybe<Scalars['Int']>;
  retailRevenueCagr?: Maybe<Scalars['Int']>;
  /** sellers related to the retailer */
  sellers?: Maybe<Array<Maybe<Seller>>>;
  status: RetailerStatus;
};

export type RetailerExpermentalConfig = {
  __typename?: 'RetailerExpermentalConfig';
  id: Scalars['ID'];
  key: Scalars['String'];
  retailer?: Maybe<Retailer>;
  value: Scalars['String'];
};

export type RetailerList = ListOffsetLimit & {
  __typename?: 'RetailerList';
  limit?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  retailers: Array<Maybe<Retailer>>;
  totalCount?: Maybe<Scalars['Int']>;
};

export type RetailerPreferenceDefaultValue = {
  __typename?: 'RetailerPreferenceDefaultValue';
  id: Scalars['ID'];
  key: Scalars['String'];
  retailerPreferences?: Maybe<RetailerPreferences>;
  value: Scalars['String'];
};

export type RetailerPreferences = {
  __typename?: 'RetailerPreferences';
  defaultValues?: Maybe<Array<Maybe<RetailerPreferenceDefaultValue>>>;
  id: Scalars['ID'];
  retailer?: Maybe<Retailer>;
};

export enum RetailerStatus {
  Active = 'ACTIVE',
  Inactive = 'INACTIVE',
  Live = 'LIVE'
}

/** Stock Keeping Unit */
export type Sku = {
  __typename?: 'SKU';
  description?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  matchingSearchPhrases?: Maybe<Array<Maybe<Scalars['String']>>>;
  name?: Maybe<Scalars['String']>;
  price?: Maybe<Scalars['Money']>;
  quantity?: Maybe<Scalars['Int']>;
  skuKey: Scalars['ID'];
};

export type SkuUpdate = {
  description?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
  matchingSearchPhrases?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
  name?: InputMaybe<Scalars['String']>;
  price?: InputMaybe<Scalars['Money']>;
  quantity?: InputMaybe<Scalars['Int']>;
  skuKey: Scalars['ID'];
};

/** Account in SalesForce */
export type SalesForceAccount = {
  __typename?: 'SalesForceAccount';
  favoriteColor?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name?: Maybe<Scalars['String']>;
  shoeSize?: Maybe<Scalars['Float']>;
};

/** Audience Segment */
export type Segment = {
  __typename?: 'Segment';
  audiences: Array<Maybe<Audience>>;
  description?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name: Scalars['String'];
};


/** Audience Segment */
export type SegmentAudiencesArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

/**
 * Sellers are a concept on many retailer platforms where products are purchased through
 *  (and even sometimes fulfilled by) a separate business contracting with the retailer.
 *  Many sellers do this to try and gain representation on a platform with an existing shopper base,
 *  and retailers do this to gain a cut of the market the seller brings (while often defraying cost and risk associated with inventory).
 */
export type Seller = {
  __typename?: 'Seller';
  id: Scalars['ID'];
  /** The name of the seller; usually this represents a business and is intended to be displayable for people to easily digest. “Ben’s House of Vintage Shoes” is a good example. */
  name: Scalars['String'];
};

/** List of SKUs pagable by offset and limit */
export type SkuList = {
  __typename?: 'SkuList';
  limit?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  skus: Array<Maybe<Sku>>;
  totalCount?: Maybe<Scalars['Int']>;
};

export type StringAttribute = {
  __typename?: 'StringAttribute';
  key: Scalars['String'];
  value?: Maybe<Scalars['String']>;
};

export type Subscription = {
  __typename?: 'Subscription';
  accountBrandedKeywordsDisabled?: Maybe<Account>;
  accountBrandedKeywordsEnabled?: Maybe<Account>;
  accountBrandsUpated?: Maybe<Account>;
  accountCountryAdded?: Maybe<Account>;
  accountCreated?: Maybe<Account>;
  accountCurrencyDataChanged?: Maybe<Account>;
  accountFeesModified?: Maybe<Account>;
  accountInitialized?: Maybe<Account>;
  accountReportingLabelModified?: Maybe<Account>;
  accountRetailerConnected?: Maybe<Retailer>;
  accountRetailersUpdated?: Maybe<Array<Maybe<Retailer>>>;
  accountSalesforceDataModified?: Maybe<SalesForceAccount>;
  accountSellerModified?: Maybe<Account>;
  accountUserAdded?: Maybe<User>;
  accountUserRemoved?: Maybe<User>;
  accountUserUpdated?: Maybe<User>;
  accountWhileLabelSettingsCreated?: Maybe<AccountSettings>;
  accountWhileLabelSettingsUpdated?: Maybe<AccountSettings>;
  campaignCreated: Campaign;
  childAccountCreated?: Maybe<Account>;
  externalUserNameUpdated?: Maybe<Account>;
  externameUserNameUpdated?: Maybe<User>;
  lineitemActivated: Lineitem;
  lineitemCreated: Lineitem;
  lineitemPaused: Lineitem;
  portfolioBrandsModified?: Maybe<Portfolio>;
  portfolioCreated?: Maybe<Portfolio>;
  portfolioMappedToUser?: Maybe<Portfolio>;
  portfolioNameModified?: Maybe<Portfolio>;
  portfolioUserAdded?: Maybe<User>;
  portfolioUserRemovedFrom?: Maybe<User>;
  portfoliosRemoved?: Maybe<Portfolio>;
  privateMarketAccountCrated?: Maybe<PrivateMarketAccount>;
  retailerInitialized?: Maybe<Retailer>;
  retailerUpdated?: Maybe<Retailer>;
  retailerWentLive?: Maybe<Retailer>;
  skuInformationModified?: Maybe<Array<Maybe<Sku>>>;
  taxonomyManuallyAdded?: Maybe<Array<Maybe<Taxonomy>>>;
};


export type SubscriptionAccountBrandedKeywordsDisabledArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountBrandedKeywordsEnabledArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountBrandsUpatedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountCountryAddedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountCurrencyDataChangedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountFeesModifiedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountInitializedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountReportingLabelModifiedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountRetailerConnectedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountRetailersUpdatedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountSalesforceDataModifiedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountSellerModifiedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountWhileLabelSettingsCreatedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionAccountWhileLabelSettingsUpdatedArgs = {
  accountId: Scalars['ID'];
};


export type SubscriptionLineitemActivatedArgs = {
  lineitemId: Scalars['ID'];
};


export type SubscriptionLineitemPausedArgs = {
  lineitemId: Scalars['ID'];
};

export type Taxonomy = {
  __typename?: 'Taxonomy';
  key?: Maybe<Scalars['ID']>;
  skus?: Maybe<SkuList>;
};


export type TaxonomySkusArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

export type UpdateAccountSettings = {
  things?: InputMaybe<Scalars['String']>;
};

export type UpdateWhiteLabelSettings = {
  things?: InputMaybe<Scalars['String']>;
};

export type User = {
  __typename?: 'User';
  backupCodeEnabled?: Maybe<Scalars['Boolean']>;
  banned?: Maybe<Scalars['Boolean']>;
  birthday?: Maybe<Scalars['String']>;
  createdAt?: Maybe<Scalars['DateTime']>;
  emailAddresses?: Maybe<Array<Maybe<EmailAddress>>>;
  externalAccounts?: Maybe<Array<Maybe<ExternalAccount>>>;
  externalId?: Maybe<Scalars['ID']>;
  firstName?: Maybe<Scalars['String']>;
  gender?: Maybe<Scalars['String']>;
  hasImage?: Maybe<Scalars['Boolean']>;
  id: Scalars['ID'];
  imageUrl?: Maybe<Scalars['String']>;
  lastName?: Maybe<Scalars['String']>;
  lastSignInAt?: Maybe<Scalars['DateTime']>;
  passwordEnabled?: Maybe<Scalars['Boolean']>;
  phoneNumbers?: Maybe<Array<Maybe<PhoneNumber>>>;
  primaryEmailAddressId?: Maybe<Scalars['String']>;
  primaryPhoneNumberId?: Maybe<Scalars['String']>;
  primaryWeb3WalletId?: Maybe<Scalars['String']>;
  privateMetadata?: Maybe<Array<Maybe<Attribute>>>;
  publicMetadata?: Maybe<Array<Maybe<Attribute>>>;
  totpEnabled?: Maybe<Scalars['Boolean']>;
  twoFactorEnabled?: Maybe<Scalars['Boolean']>;
  unsafeMetadata?: Maybe<Array<Maybe<Attribute>>>;
  updatedAt?: Maybe<Scalars['DateTime']>;
  username?: Maybe<Scalars['String']>;
  web3Wallets?: Maybe<Array<Maybe<Web3Wallet>>>;
};

export type Verification = {
  __typename?: 'Verification';
  attempts?: Maybe<Scalars['Int']>;
  expireAt?: Maybe<Scalars['Int']>;
  externalVerificationRedirectURL?: Maybe<Scalars['URL']>;
  nonce?: Maybe<Scalars['String']>;
  status?: Maybe<Scalars['String']>;
  strategy?: Maybe<Scalars['String']>;
};

export type Web3Wallet = {
  __typename?: 'Web3Wallet';
  id?: Maybe<Scalars['ID']>;
  verification?: Maybe<Verification>;
  web3Wallet?: Maybe<Scalars['String']>;
};

export type AccountsQueryVariables = Exact<{
  retailerId?: InputMaybe<Scalars['ID']>;
}>;


export type AccountsQuery = { __typename?: 'Query', accounts: Array<{ __typename?: 'Account', id: string, name: string, type?: AccountType | null, accountExternalId?: string | null, currency?: { __typename?: 'Currency', code: CurrencyCode, name?: string | null, symbol?: string | null } | null, countries?: Array<{ __typename?: 'Country', code: CountryCode, name: string } | null> | null, retailers?: Array<{ __typename?: 'Retailer', id: string, name: string, status: RetailerStatus } | null> | null } | null> };

export type AccountQueryVariables = Exact<{
  accountId: Scalars['ID'];
}>;


export type AccountQuery = { __typename?: 'Query', account?: { __typename?: 'Account', id: string, name: string, type?: AccountType | null, fee?: { __typename?: 'AccountFee', accountServicingFee?: number | null, demandSideFee?: number | null, isCommerceDisplayManagedServiceFee?: boolean | null, isSponsoredProductsManagedServiceFee?: boolean | null, startDate?: Date | null, supplySideFee?: number | null } | null, currency?: { __typename?: 'Currency', name?: string | null, code: CurrencyCode, symbol?: string | null } | null, countries?: Array<{ __typename?: 'Country', code: CountryCode, name: string } | null> | null, retailers?: Array<{ __typename?: 'Retailer', id: string, name: string, status: RetailerStatus } | null> | null } | null };

export type NewAccountMutationVariables = Exact<{
  account: NewAccount;
}>;


export type NewAccountMutation = { __typename?: 'Mutation', newAccount?: { __typename?: 'Account', id: string, name: string, type?: AccountType | null } | null };

export type MapAccountRetailersMutationVariables = Exact<{
  accountId: Scalars['ID'];
  retailerIds: Array<InputMaybe<Scalars['ID']>> | InputMaybe<Scalars['ID']>;
}>;


export type MapAccountRetailersMutation = { __typename?: 'Mutation', mapAccountRetailers?: Array<{ __typename?: 'Retailer', id: string, name: string, status: RetailerStatus } | null> | null };

export type AccountCreatedSubscriptionVariables = Exact<{ [key: string]: never; }>;


export type AccountCreatedSubscription = { __typename?: 'Subscription', accountCreated?: { __typename?: 'Account', id: string, name: string } | null };

export type BrandsQueryVariables = Exact<{
  offset?: InputMaybe<Scalars['Int']>;
  limit?: InputMaybe<Scalars['Int']>;
}>;


export type BrandsQuery = { __typename?: 'Query', brands?: { __typename?: 'BrandList', totalCount?: number | null, offset?: number | null, limit?: number | null, brands: Array<{ __typename?: 'Brand', id: string, name: string, foundedIn?: string | null, country?: string | null, brandValue?: number | null, industry?: string | null } | null> } | null };

export type BrandQueryVariables = Exact<{
  brandId: Scalars['ID'];
}>;


export type BrandQuery = { __typename?: 'Query', brand?: { __typename?: 'Brand', id: string, name: string, foundedBy?: string | null, foundedIn?: string | null, country?: string | null, keyPeople?: string | null, industry?: string | null, website?: string | null, rank?: number | null, brandValue?: number | null, rating?: string | null } | null };

export type CampaignsQueryVariables = Exact<{
  accountId?: InputMaybe<Scalars['ID']>;
  retailerId?: InputMaybe<Scalars['ID']>;
  brandId?: InputMaybe<Scalars['ID']>;
  page?: InputMaybe<Scalars['Int']>;
  size?: InputMaybe<Scalars['Int']>;
}>;


export type CampaignsQuery = { __typename?: 'Query', campaigns?: { __typename?: 'CampaignList', totalCount?: number | null, page?: number | null, size?: number | null, campaigns?: Array<{ __typename?: 'Campaign', id: string, name?: string | null, status?: CampaignStatus | null, startDate?: Date | null, endDate?: Date | null, type?: CampaignType | null, budget?: { __typename?: 'CampaignBudget', amount?: number | null, isCapped?: boolean | null, type?: BudgetType | null } | null } | null> | null } | null };

export type CampaignQueryVariables = Exact<{
  campaignId: Scalars['ID'];
}>;


export type CampaignQuery = { __typename?: 'Query', campaign?: { __typename?: 'Campaign', id: string, name?: string | null, status?: CampaignStatus | null, type?: CampaignType | null, startDate?: Date | null, endDate?: Date | null, lineitems?: { __typename?: 'LineitemList', totalCount?: number | null, lineitems?: Array<{ __typename?: 'Lineitem', id: string, name: string, status?: LineitemStatus | null, startDate?: Date | null, endDate?: Date | null, budget?: { __typename?: 'LineitemBudget', amount?: number | null, isCapped?: boolean | null, type?: BudgetType | null } | null } | null> | null } | null, budget?: { __typename?: 'CampaignBudget', amount?: number | null, isCapped?: boolean | null, type?: BudgetType | null } | null } | null };

export type NewCampaignMutationVariables = Exact<{
  advertiserId: Scalars['ID'];
  campaign: NewCampaign;
}>;


export type NewCampaignMutation = { __typename?: 'Mutation', newCampaign?: { __typename?: 'Campaign', id: string, name?: string | null } | null };

export type LineitemsQueryVariables = Exact<{
  campaignId: Scalars['ID'];
  offset?: InputMaybe<Scalars['Int']>;
  limit?: InputMaybe<Scalars['Int']>;
}>;


export type LineitemsQuery = { __typename?: 'Query', lineitems?: { __typename?: 'LineitemList', totalCount?: number | null, offset?: number | null, limit?: number | null, lineitems?: Array<{ __typename?: 'Lineitem', id: string, name: string, startDate?: Date | null, endDate?: Date | null, status?: LineitemStatus | null, budget?: { __typename?: 'LineitemBudget', amount?: number | null, isCapped?: boolean | null, type?: BudgetType | null } | null } | null> | null } | null };

export type LineitemQueryVariables = Exact<{
  lineitemId: Scalars['ID'];
}>;


export type LineitemQuery = { __typename?: 'Query', lineitem?: { __typename?: 'Lineitem', id: string, name: string, startDate?: Date | null, endDate?: Date | null, status?: LineitemStatus | null, financialStatus?: FinancialStatus | null, campaign?: { __typename?: 'Campaign', id: string, name?: string | null } | null, budget?: { __typename?: 'LineitemBudget', amount?: number | null, isCapped?: boolean | null, type?: BudgetType | null } | null } | null };

export type NewLineitemMutationVariables = Exact<{
  campaignId: Scalars['ID'];
  lineitem: NewLineitem;
}>;


export type NewLineitemMutation = { __typename?: 'Mutation', newLineitem?: { __typename?: 'Lineitem', id: string, name: string, startDate?: Date | null, status?: LineitemStatus | null, endDate?: Date | null } | null };

export type ActivateLineitemsMutationVariables = Exact<{
  lineitemIds: Array<InputMaybe<Scalars['ID']>> | InputMaybe<Scalars['ID']>;
}>;


export type ActivateLineitemsMutation = { __typename?: 'Mutation', activateLineitems: Array<{ __typename?: 'Lineitem', id: string, name: string, startDate?: Date | null, status?: LineitemStatus | null, endDate?: Date | null } | null> };

export type PauseLineitemsMutationVariables = Exact<{
  lineitemIds: Array<InputMaybe<Scalars['ID']>> | InputMaybe<Scalars['ID']>;
}>;


export type PauseLineitemsMutation = { __typename?: 'Mutation', pauseLineitems: Array<{ __typename?: 'Lineitem', id: string, name: string, startDate?: Date | null, status?: LineitemStatus | null, endDate?: Date | null } | null> };

export type LineitemActivatedSubscriptionVariables = Exact<{
  lineitemId: Scalars['ID'];
}>;


export type LineitemActivatedSubscription = { __typename?: 'Subscription', lineitemActivated: { __typename?: 'Lineitem', id: string, name: string, status?: LineitemStatus | null } };

export type LineitemPausedSubscriptionVariables = Exact<{
  lineitemId: Scalars['ID'];
}>;


export type LineitemPausedSubscription = { __typename?: 'Subscription', lineitemPaused: { __typename?: 'Lineitem', id: string, name: string, status?: LineitemStatus | null } };

export type AllCountriesQueryVariables = Exact<{ [key: string]: never; }>;


export type AllCountriesQuery = { __typename?: 'Query', countries: Array<{ __typename?: 'Country', name: string, code: CountryCode, currency: CurrencyCode } | null> };

export type SkuQueryVariables = Exact<{
  skuKey: Scalars['ID'];
}>;


export type SkuQuery = { __typename?: 'Query', sku?: { __typename?: 'SKU', skuKey: string, name?: string | null, description?: string | null, quantity?: number | null, price?: number | null, matchingSearchPhrases?: Array<string | null> | null, image?: string | null } | null };

export type SkusQueryVariables = Exact<{
  offset?: InputMaybe<Scalars['Int']>;
  limit?: InputMaybe<Scalars['Int']>;
}>;


export type SkusQuery = { __typename?: 'Query', skus?: { __typename?: 'SkuList', offset?: number | null, limit?: number | null, totalCount?: number | null, skus: Array<{ __typename?: 'SKU', skuKey: string, name?: string | null, description?: string | null, image?: string | null, quantity?: number | null, price?: number | null } | null> } | null };

export type RetailerQueryVariables = Exact<{
  retailerId: Scalars['ID'];
}>;


export type RetailerQuery = { __typename?: 'Query', retailer?: { __typename?: 'Retailer', id: string, name: string, status: RetailerStatus, rank?: number | null, countryOfOrigin?: string | null, retailRevenue?: number | null, parentRevenue?: number | null, parentCompanyNetIncome?: number | null, operationalFormat?: string | null, countriesOfOperation?: number | null, retailRevenueCagr?: number | null } | null };

export type RetailersQueryVariables = Exact<{
  offset?: InputMaybe<Scalars['Int']>;
  limit?: InputMaybe<Scalars['Int']>;
}>;


export type RetailersQuery = { __typename?: 'Query', retailers: { __typename?: 'RetailerList', limit?: number | null, offset?: number | null, totalCount?: number | null, retailers: Array<{ __typename?: 'Retailer', id: string, name: string, status: RetailerStatus, countryOfOrigin?: string | null } | null> } };
